### PR TITLE
reordered sidebar

### PR DESCRIPTION
**Pull request by Piratepie**
- renamed dashboard -> stats
- setup flights as default page

### CODE REVIEW

**Comment by tomassabol** [comment]
please provide screenshots

**Comment by Piratepie** [comment]
image

**Comment by Piratepie** [comment]
Icons aren't permanent

**Review by tomassabol — CHANGES_REQUESTED** [review]
center the navbar options with the logout text and logo

**Comment by Piratepie** [comment]
Merging for now, we'll discuss design pet peeves later

**Pull request merged**
