### PR TITLE
61 apply brandbook branding to app

### PR DESCRIPTION
**Pull request by Piratepie**
- changed fonts
- changed colors
- hid paths that currently don't work

### CODE REVIEW

**Comment by Piratepie** [comment]
> provide screenshots

> Draft
Will come later

**Comment by Piratepie** [comment]
What are we thinking team?
image
image
image
image

**Comment by ttommmy** [comment]
If it's not too much, could you center these textfields vertically?
image

Or does it look like that only on the emulator?

**Comment by Piratepie** [comment]
> If it's not too much, could you center these textfields vertically? image
> 
> Or does it look like that only on the emulator?

This is done on purpose to group the text and it's input field together, makes it a little clearer as to what text prompt is linked to what input field

**Pull request merged**
