### PR TITLE
Create flutter.yml

### PR DESCRIPTION
**Pull request by mazonk**
Flutter pipeline

### CODE REVIEW

**Review by Piratepie — APPROVED** [review]

**Review by tomassabol — CHANGES_REQUESTED** [review]
it failed ☹️

**Comment by mazonk** [comment]
yay!

**Comment by Piratepie** [comment]
This solves #10

**Review by tomassabol — CHANGES_REQUESTED** [review]
implement it for dev branch as well and specify the path. i think it will fail otherwise (main branch doesn't contain any flutter code for now)

**Comment by tomassabol** [comment]
@mazonk resolve the conflict please

**Review by tomassabol — CHANGES_REQUESTED** [review]
revert this commit. the code will fail for now as there is no flutter code in the /client directory on main. but the action is indeed setup correctly

**Pull request merged**
